In [95]:
import numpy as np
import pandas as pd
from IPython.core.display import display_webp
from numpy.ma.extras import average

energy = pd.read_excel('data/Energy_Indicators.xls', skiprows=17, skipfooter=38, usecols=[2,3,4,5], names=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'])
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_rows', None)

# Petajoules to Gigajoules conversion
energy.loc[:226, 'Energy Supply'] = energy.loc[:226, 'Energy Supply'] * 1000000


# Changed ... to np.NaN
energy = energy.replace(r'\.+', np.nan, regex=True)

# Delete numbers/parenthesis in the names
# \d+ — one or more digits
# | — or
# \(.*?\) — anything inside parentheses

energy['Country'] = energy['Country'].str.replace(r'\d+|\(.*?\)', '', regex=True)


# Changed names of countries
energy['Country'] = energy['Country'].replace(
    ['Republic of Korea', 'United States of America', 'United Kingdom of Great Britain and Northern Ireland', 'China, Hong Kong Special Administrative Region'],
    ['South Korea', 'United States', 'United Kingdom', 'Hong Kong'],
)

print("\nFinal result")


display(energy)

Final result

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321000000,10,78.67
1,Albania,102000000,35,100.00
2,Algeria,1959000000,51,0.55
3,American Samoa,NaN,NaN,0.64
4,Andorra,9000000,121,88.70
5,Angola,642000000,27,70.91
6,Anguilla,2000000,136,0.00
7,Antigua and Barbuda,8000000,84,0.00
8,Argentina,3378000000,79,24.06
9,Armenia,143000000,48,28.24
10,Aruba,12000000,120,14.87
11,Australia,5386000000,231,11.81
12,Austria,1391000000,164,72.45
13,Azerbaijan,567000000,60,6.38
14,Bahamas,45000000,118,0.00
15,Bahrain,574000000,425,0.00
16,Bangladesh,1625000000,10,1.97
17,Barbados,19000000,69,0.00
18,Belarus,1142000000,120,0.46
19,Belgium,2338000000,210,9.96
20,Belize,13000000,39,64.69
21,Benin,170000000,16,0.00
22,Bermuda,6000000,88,0.00
23,Bhutan,63000000,83,100.00
24,Bolivia,336000000,32,31.48
25,"Bonaire, Sint Eustatius and Saba",5000000,213,0.00
26,Bosnia and Herzegovina,266000000,70,41.46
27,Botswana,86000000,39,0.13
28,Brazil,12149000000,59,69.65
29,British Virgin Islands,2000000,85,0.00
30,Brunei Darussalam,127000000,310,0.05
31,Bulgaria,703000000,97,17.23
32,Burkina Faso,164000000,10,14.50
33,Burundi,58000000,6,86.79
34,Cabo Verde,7000000,15,21.23
35,Cambodia,250000000,17,57.31
36,Cameroon,307000000,14,70.89
37,Canada,10431000000,296,61.95
38,Cayman Islands,8000000,131,0.00
39,Central African Republic,23000000,5,85.64
40,Chad,77000000,6,0.00
41,Chile,1613000000,92,28.01
42,China,127191000000,93,19.75
43,Hong Kong,585000000,82,0.00
44,"China, Macao Special Administrative Region",47000000,83,0.00
45,Colombia,1513000000,32,63.00
46,Comoros,5000000,7,11.63
47,Congo,102000000,23,57.75
48,Cook Islands,1000000,48,0.00
49,Costa Rica,222000000,47,88.74
50,Côte d'Ivoire,547000000,25,22.82
51,Croatia,321000000,75,64.28
52,Cuba,585000000,51,0.66
53,Curaçao,78000000,502,0.00
54,Cyprus,82000000,71,6.48
55,Czech Republic,1751000000,166,7.07
56,Democratic People's Republic of Korea,612000000,25,70.18
57,Democratic Republic of the Congo,888000000,12,99.59
58,Denmark,725000000,129,33.54
59,Djibouti,11000000,13,0.00
60,Dominica,2000000,28,36.63
61,Dominican Republic,339000000,33,11.25
62,Ecuador,680000000,43,47.71
63,Egypt,3422000000,39,8.81
64,El Salvador,176000000,29,56.45
65,Equatorial Guinea,73000000,91,6.36
66,Eritrea,34000000,7,0.55
67,Estonia,258000000,195,4.18
68,Ethiopia,1394000000,15,99.91
69,Faeroe Islands,9000000,179,38.57
70,Falkland Islands,1000000,258,33.33
71,Fiji,31000000,36,62.00
72,Finland,1374000000,252,19.54
73,France,10597000000,166,17.02
74,French Guiana,13000000,52,62.00
75,French Polynesia,12000000,44,26.86
76,Gabon,99000000,60,37.50
77,Gambia,14000000,7,0.00
78,Georgia,163000000,40,82.22
79,Germany,13261000000,165,17.90
80,Ghana,316000000,12,63.10
81,Gibraltar,8000000,245,0.00
82,Greece,993000000,90,24.80
83,Greenland,9000000,166,78.12
84,Grenada,5000000,43,0.00
85,Guadeloupe,33000000,70,14.81
86,Guam,NaN,NaN,0.00
87,Guatemala,452000000,29,49.52
88,Guernsey,0,6,0.00
89,Guinea,145000000,12,48.44
90,Guinea-Bissau,29000000,17,0.00
91,Guyana,34000000,45,0.00
92,Haiti,172000000,16,12.76
93,Honduras,217000000,28,37.76
94,Hungary,947000000,95,3.26
95,Iceland,312000000,957,99.97
96,India,33195000000,26,14.97
97,Indonesia,8754000000,35,12.19
98,Iran,9172000000,119,5.71
99,Iraq,2077000000,61,7.87
100,Ireland,548000000,117,20.92
101,Isle of Man,0,4,0.79
102,Israel,997000000,128,0.87
103,Italy,6530000000,109,33.67
104,Jamaica,108000000,39,5.62
105,Japan,18984000000,149,10.23
106,Jersey,3000000,34,0.00
107,Jordan,325000000,45,0.34
108,Kazakhstan,3548000000,208,8.11
109,Kenya,873000000,20,73.76
110,Kiribati,1000000,8,0.00
111,Kuwait,1475000000,410,0.00
112,Kyrgyzstan,167000000,29,93.48
113,Lao People's Democratic Republic,85000000,13,93.29
114,Latvia,183000000,91,48.83
115,Lebanon,289000000,55,6.61
116,Lesotho,48000000,23,100.00
117,Liberia,83000000,19,0.00
118,Libya,707000000,113,0.00
119,Liechtenstein,3000000,79,96.47
120,Lithuania,282000000,95,41.03
121,Luxembourg,168000000,307,45.53
122,Madagascar,166000000,7,50.82
123,Malawi,101000000,6,89.14
124,Malaysia,3417000000,116,7.75
125,Maldives,15000000,43,0.00
126,Mali,66000000,4,64.77
127,Malta,31000000,75,1.42
128,Marshall Islands,1000000,28,0.00
129,Martinique,33000000,84,2.61
130,Mauritania,51000000,13,0.00
131,Mauritius,58000000,46,3.53
132,Mexico,7944000000,64,12.91
133,Micronesia,2000000,21,2.94
134,Mongolia,475000000,166,0.00
135,Montenegro,42000000,67,65.58
136,Montserrat,1000000,153,0.00
137,Morocco,796000000,23,15.89
138,Mozambique,469000000,18,94.63
139,Myanmar,682000000,13,72.04
140,Namibia,63000000,27,95.79
141,Nauru,1000000,60,0.00
142,Nepal,458000000,16,99.68
143,Netherlands,3199000000,190,6.32
144,New Caledonia,51000000,200,20.43
145,New Zealand,876000000,196,72.87
146,Nicaragua,149000000,25,40.76
147,Niger,87000000,5,0.00
148,Nigeria,5589000000,32,18.39
149,Niue,0,65,0.00
150,Northern Mariana Islands,NaN,NaN,0.00
151,Norway,1388000000,273,97.64
152,Oman,1015000000,260,0.00
153,Pakistan,2868000000,16,31.88
154,Palau,3000000,152,18.75
155,Panama,158000000,42,57.51
156,Papua New Guinea,144000000,20,23.95
157,Paraguay,228000000,35,100.00
158,Peru,858000000,28,51.97
159,Philippines,1781000000,18,26.17
160,Poland,4121000000,107,5.54
161,Portugal,899000000,86,53.34
162,Puerto Rico,56000000,15,1.08
163,Qatar,1396000000,664,0.00
164,South Korea,11007000000,221,2.28
165,Republic of Moldova,93000000,23,5.08
166,Réunion,59000000,70,28.30
167,Romania,1339000000,68,34.38
168,Russian Federation,30709000000,214,17.29
169,Rwanda,95000000,9,35.84
170,Saint Helena,0,40,9.09
171,Saint Kitts and Nevis,4000000,73,0.00
172,Saint Lucia,6000000,33,0.00
173,Saint Pierre and Miquelon,1000000,162,2.13
174,Saint Vincent and the Grenadines,3000000,28,16.67
175,Samoa,4000000,22,31.36
176,Sao Tome and Principe,3000000,14,10.45
177,Saudi Arabia,7985000000,264,0.00
178,Senegal,154000000,11,2.00
179,Serbia,618000000,69,27.22
180,Seychelles,9000000,94,1.98
181,Sierra Leone,67000000,11,64.02
182,Singapore,1120000000,207,0.00
183,Sint Maarten,12000000,327,0.00
184,Slovakia,711000000,131,20.22
185,Slovenia,287000000,139,31.86
186,Solomon Islands,6000000,11,0.00
187,Somalia,126000000,12,0.00
188,South Africa,6341000000,119,1.69
189,South Sudan,28000000,2,0.42
190,Spain,4923000000,106,37.97
191,Sri Lanka,388000000,19,59.57
192,State of Palestine,61000000,14,0.00
193,Sudan,608000000,16,78.41
194,Suriname,34000000,65,22.02
195,Swaziland,49000000,39,40.68
196,Sweden,2044000000,212,46.60
197,Switzerland,1113000000,136,57.75
198,Syrian Arab Republic,542000000,28,11.57
199,Tajikistan,106000000,13,99.74
200,Thailand,5336000000,79,4.31
201,The former Yugoslav Republic of Macedonia,117000000,56,26.14
202,Timor-Leste,7000000,6,0.00
203,Togo,134000000,19,80.18
204,Tonga,3000000,28,0.00
205,Trinidad and Tobago,824000000,611,0.00
206,Tunisia,430000000,39,3.49
207,Turkey,4897000000,64,28.54
208,Turkmenistan,1102000000,210,0.00
209,Turks and Caicos Islands,3000000,85,0.00
210,Tuvalu,NaN,NaN,0.00
211,Uganda,452000000,12,68.02
212,Ukraine,4844000000,107,8.07
213,United Arab Emirates,2710000000,300,0.00
214,United Kingdom,7920000000,124,10.60
215,United Republic of Tanzania,994000000,20,31.07
216,United States,90838000000,286,11.57
217,United States Virgin Islands,NaN,NaN,0.00
218,Uruguay,196000000,58,71.61
219,Uzbekistan,1798000000,62,21.33
220,Vanuatu,3000000,10,14.71
221,Venezuela,2871000000,95,67.83
222,Viet Nam,2554000000,28,45.32
223,Wallis and Futuna Islands,0,26,0.00
224,Yemen,344000000,13,0.00
225,Zambia,400000000,26,99.71
226,Zimbabwe,480000000,32,52.54

In [96]:
GDP = pd.read_csv('data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_133326.csv', skiprows=4)

GDP = GDP.replace(['Korea, Rep.', 'Iran, Islamic Rep.', 'Hong Kong SAR, China'],
                  ['South Korea', 'Iran', 'Hong Kong'])

display(GDP)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3092427932.96,3276187709.50,3346623191.46,2471419181.72,2880902798.92,3324034443.27,3834729616.12,4265650673.00,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,24205688712.38,24958886027.46,27073233856.54,31769135008.65,30279553206.64,33806176716.85,...,978076465866.45,1020955778298.17,1018714795912.35,938607563405.09,1114144799994.21,1228967879390.01,1179359054880.45,1242693542929.85,NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,18753456497.82,18053222687.41,18799444490.11,19955929052.15,14259995441.08,14497243872.13,17152234636.87,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,11904805741.68,12707719290.63,13630588814.30,14468913698.05,15803564796.41,16920876929.66,...,694051345937.23,777840323023.31,1026996211935.80,963784699293.98,1026651004045.79,1063649130876.99,938238370514.20,736384961061.52,NaN,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,84376935689.34,89512794227.49,80734428592.54,58852456453.88,79559543805.30,131212208930.34,107167747140.13,100998916781.08,NaN,NaN
5,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,13258268435.60,15379508329.76,15585111614.04,15241458744.59,18031989573.03,19017247013.88,23491242727.41,27046429296.67,NaN,NaN
6,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3000160414.64,3218418631.68,3155150255.91,2891002460.29,3324648075.56,3380611694.73,3785065524.85,4039842405.48,NaN,NaN
7,Arab World,ARB,GDP (current US$),NY.GDP.MKTP.CD,NaN,19998438484.73,20329047307.12,22364472061.30,24813307353.86,26771102387.35,...,2611323720520.00,2920829737234.67,2965285548936.01,2604104981819.80,3085141461685.60,3747416641077.46,3622495663981.78,3735881442514.35,NaN,NaN
8,United Arab Emirates,ARE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,403365010211.03,440560108917.63,433926208304.97,357161878829.14,422441388699.80,511403403675.97,522622191967.33,552324846834.58,NaN,NaN
9,Argentina,ARG,GDP (current US$),NY.GDP.MKTP.CD,15865474315.41,20132220374.91,18337691145.37,18272123664.47,25605249381.76,28344705966.64,...,643628393281.36,524819892360.18,447754683615.22,385740508436.97,486564085480.04,633993756301.08,649461687959.17,638365455340.04,NaN,NaN
10,Armenia,ARM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,11527458709.02,12457940694.74,13619290539.21,12641698583.22,13878908628.94,19513506553.13,24185982215.65,25955275380.03,NaN,NaN
11,American Samoa,ASM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,612000000.00,639000000.00,647000000.00,721000000.00,750000000.00,871000000.00,NaN,NaN,NaN,NaN
12,Antigua and Barbuda,ATG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1534855555.56,1661529629.63,1726448148.15,1411637037.04,1602125925.93,1866566666.67,2005785185.19,2207622874.07,NaN,NaN
13,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,18635682981.71,19713123154.10,19953923192.63,21573443451.75,23835843813.74,26014244162.28,...,1330890554614.09,1433144978761.67,1398349602956.35,1333336461648.09,1560617493202.69,1695627535475.80,1734451264655.60,1757022451652.83,NaN,NaN
14,Austria,AUT,GDP (current US$),NY.GDP.MKTP.CD,6624086313.14,7346566037.83,7793042529.16,8414050621.02,9213648655.98,10041659445.12,...,414926138132.69,452582294972.78,442983642371.84,434397601557.70,480466363176.81,473221298968.22,516670509628.88,534790720466.82,NaN,NaN
15,Azerbaijan,AZE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,40866627351.98,47112470051.77,48174235294.12,42693000000.00,54825411764.71,78807470588.24,72428470588.24,74315882352.94,NaN,NaN
16,Burundi,BDI,GDP (current US$),NY.GDP.MKTP.CD,195999990.00,202999992.00,213500006.00,232749998.00,260750008.00,158994962.96,...,2831362208.34,2913411408.45,2871555326.31,3227847281.32,3435598072.79,4036192552.89,3430949249.91,3082433067.33,NaN,NaN
17,Belgium,BEL,GDP (current US$),NY.GDP.MKTP.CD,11810619368.39,12561701694.33,13436827166.52,14445805381.39,16168044450.25,17597783297.46,...,500908767351.53,542638913427.92,536726344405.49,529694473501.79,598522422241.85,591085783326.27,651330595110.01,671370081636.41,NaN,NaN
18,Benin,BEN,GDP (current US$),NY.GDP.MKTP.CD,226195578.43,235668220.51,236434954.04,253927697.26,269819005.88,289908680.43,...,12701655836.95,14262408089.93,14391686313.46,15686741883.93,17687623530.34,17425405090.86,19673291004.14,21482643706.42,NaN,NaN
19,Burkina Faso,BFA,GDP (current US$),NY.GDP.MKTP.CD,330442815.82,350247234.26,379567099.25,394040667.11,410321644.96,422916789.75,...,14106955615.34,15890066221.29,16032813503.37,17725010532.53,19697516284.38,18622421394.61,20112614449.20,23124729853.02,NaN,NaN
20,Bangladesh,BGD,GDP (current US$),NY.GDP.MKTP.CD,4274894083.33,4817580375.00,5081413541.67,5319458562.50,5386054833.33,5906636791.67,...,293732446624.60,321362752441.78,351231654603.69,373979442362.19,416271647911.01,460131689083.08,437415333018.29,450119432068.85,NaN,NaN
21,Bulgaria,BGR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,59167647387.61,66097226262.22,68507731353.91,70486877546.49,84374613233.36,90506153293.67,102199231384.54,113343355779.99,NaN,NaN
22,Bahrain,BHR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,37204813829.79,39567978723.40,40446808510.64,35837632978.72,40840212765.96,46458191489.36,46192260638.30,47109734308.51,NaN,NaN
23,"Bahamas, The",BHS,GDP (current US$),NY.GDP.MKTP.CD,169736027.16,190022030.40,212170033.95,237650038.02,266560042.65,300272048.04,...,12446900000.00,12819200000.00,13277000000.00,10363200000.00,12037000000.00,13896800000.00,15271300000.00,15832800000.00,NaN,NaN
24,Bosnia and Herzegovina,BIH,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,18326373135.61,20484058033.11,20482608984.33,20226038369.92,23672712121.27,24534663636.18,27592361498.41,29613572022.90,NaN,NaN
25,Belarus,BLR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,54725405751.16,60031026576.26,64410170653.46,61371673344.74,69673747131.87,73775179924.60,72478760370.43,75961865471.91,NaN,NaN
26,Belize,BLZ,GDP (current US$),NY.GDP.MKTP.CD,28072478.07,29964999.96,31857591.86,33750113.75,36194586.19,40110040.11,...,2266028250.00,2285915050.00,2381187850.00,2047284600.00,2428606250.00,2846604350.00,3052362650.00,3203631800.00,NaN,NaN
27,Bermuda,BMU,GDP (current US$),NY.GDP.MKTP.CD,72400000.00,76500000.00,80700000.00,82600000.00,92200000.00,98000000.00,...,7142316000.00,7225977000.00,7423465000.00,6887364000.00,7290037000.00,7874381000.00,8579242000.00,9233600000.00,NaN,NaN
28,Bolivia,BOL,GDP (current US$),NY.GDP.MKTP.CD,377020202.02,410101010.10,448400673.40,482828282.83,544023569.02,604377104.38,...,45927439594.79,48414038842.26,49056643589.00,42313784081.04,47877892402.32,50959081953.69,52340206946.45,54881327452.97,NaN,NaN
29,Brazil,BRA,GDP (current US$),NY.GDP.MKTP.CD,17030465539.39,17275940449.38,19231747851.53,23287712878.20,20963733694.97,22465522884.10,...,2063514688805.78,1916933708352.71,1873288158838.63,1476107292151.95,1670647464062.96,1951923832083.87,2191131869706.02,2185821648943.86,NaN,NaN
30,Barbados,BRB,GDP (current US$),NY.GDP.MKTP.CD,80021846.95,85363759.34,88782583.46,99893761.27,99252731.45,105021996.86,...,5683150000.00,6001950000.00,6161850000.00,5407050000.00,5947550000.00,6884900000.00,7223250000.00,7498050000.00,NaN,NaN
31,Brunei Darussalam,BRN,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,114039500.59,...,12128168045.12,13566908391.09,13469235364.70,12005799653.98,14006496617.45,16681536466.72,15095084656.16,15340808592.48,NaN,NaN
32,Bhutan,BTN,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2591358009.20,2583335721.86,2735683570.46,2457604333.91,2768802960.11,2898227743.76,3012896789.25,NaN,NaN,NaN
33,Botswana,BWA,GDP (current US$),NY.GDP.MKTP.CD,30411413.66,32902612.87,35644956.64,38091842.85,41616347.79,45788696.33,...,16105155856.77,17031943186.14,16725908148.55,14960251607.81,18750182236.22,20321150599.15,19411266967.10,19402063512.91,NaN,NaN
34,Central African Republic,CAF,GDP (current US$),NY.GDP.MKTP.CD,112155598.49,123134583.46,124482773.83,129379123.76,142025078.74,150574795.41,...,2072349972.68,2220979146.11,2221301351.44,2326720900.38,2516498412.46,2382618615.02,2555492085.95,2751494281.07,NaN,NaN
35,Canada,CAN,GDP (current US$),NY.GDP.MKTP.CD,40563768946.95,41038192837.90,42336211555.83,45140337826.99,49503663836.37,54649410478.52,...,1649265644244.09,1725329192783.02,1743725183672.52,1655684730000.19,2022378748423.23,2190411080134.32,2173339670064.33,2243636826633.76,NaN,NaN
36,Central Europe and the Baltics,CEB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1467501784248.85,1656383422202.66,1684318282245.77,1678294256145.30,1926347717339.00,1954419184114.96,2273205742208.30,2462005273603.48,NaN,NaN
37,Switzerland,CHE,GDP (current US$),NY.GDP.MKTP.CD,10412232620.53,11713348834.31,12989649694.28,14283872299.05,15833133857.63,16780226225.08,...,695200833086.50,725568717468.00,721369112726.72,741999406005.63,815309330986.72,828508926958.39,894424821645.20,936564198048.52,NaN,NaN
38,Channel Islands,CHI,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,9170044517.20,10026394043.61,10031864649.08,9439810769.23,11157540109.89,11308272505.18,12507320838.39,NaN,NaN,NaN
39,Chile,CHL,GDP (current US$),NY.GDP.MKTP.CD,4211103676.74,4948564550.91,5765971144.47,5702520146.03,6065708668.33,6183988944.35,...,276154259981.10,295857562991.71,278285058719.47,254042159309.31,315325547162.07,301226575540.24,335518054097.64,330267137371.59,NaN,NaN
40,China,CHN,GDP (current US$),NY.GDP.MKTP.CD,59846235024.73,50162299349.79,47310737754.23,50812227918.58,59821862703.40,70565994356.18,...,12537559062282.90,14147765772963.80,14560167101283.40,14996414166715.10,18201698719564.00,18316765021690.20,18270356654533.20,18743803170827.20,NaN,NaN
41,Cote d'Ivoire,CIV,GDP (current US$),NY.GDP.MKTP.CD,546203559.34,618245634.18,645284473.73,761047198.03,921063326.59,919771228.82,...,52512343996.69,58522477786.69,60382894697.36,63027852805.42,72794636653.78,70922824813.91,80780312569.16,87113179149.28,NaN,NaN
42,Cameroon,CMR,GDP (current US$),NY.GDP.MKTP.CD,614206068.50,652777608.32,694247864.38,718320845.04,776650176.90,814083265.51,...,36098547033.17,39955552189.79,39667757527.66,40773241177.05,45011937346.84,44347206072.55,48814501547.43,53296694320.21,NaN,NaN
43,"Congo, Dem. Rep.",COD,GDP (current US$),NY.GDP.MKTP.CD,3359404117.65,3086746857.14,3779841428.57,6213185742.57,2881545272.73,4043901818.18,...,37537521565.53,46659954092.49,46845900350.03,46691989748.92,59067289573.51,70422346142.20,69843655425.29,70962185790.71,NaN,NaN
44,"Congo, Rep.",COG,GDP (current US$),NY.GDP.MKTP.CD,131731862.78,151675738.93,166521239.65,172233430.66,185693724.91,198318064.03,...,11834473039.36,14773900288.51,13976637779.98,11468687464.00,14825690210.92,15817030154.69,15321055822.52,15719986076.65,NaN,NaN
45,Colombia,COL,GDP (current US$),NY.GDP.MKTP.CD,4031152976.64,4540447761.19,4955543963.37,4836166666.67,5973366666.67,5760761904.76,...,311866875156.88,334198218098.28,323031701192.84,270348342541.46,318524633225.40,345632492851.45,366291836137.92,418818154879.27,NaN,NaN
46,Comoros,COM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1077439756.59,1178530633.25,1187915408.87,1218763671.27,1272238390.86,1222485532.32,1326836543.01,1440991455.45,NaN,NaN
47,Cabo Verde,CPV,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1996741539.95,2205099507.00,2252177124.32,1821565613.69,2051842618.71,2247003344.34,2504525548.71,2725414150.73,NaN,NaN
48,Costa Rica,CRI,GDP (current US$),NY.GDP.MKTP.CD,507513829.99,490325181.61,479180824.35,511902136.81,542578367.24,592981162.26,...,60516044656.52,62420164991.54,64417670521.35,62395610760.05,64960725734.20,69243626028.59,86497941439.02,95350423176.60,NaN,NaN
49,Caribbean small states,CSS,GDP (current US$),NY.GDP.MKTP.CD,1165303060.29,1272022469.11,1356047349.50,1447988752.00,1546223257.53,1658476310.99,...,59690101434.35,61252081219.87,62185458482.71,53320869430.71,62687149265.45,78506430710.73,79534673452.94,90344593407.05,NaN,NaN
50,Cuba,CUB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,96850649700.00,100050036100.00,103427600000.00,107352000000.00,NaN,NaN,NaN,NaN,NaN,NaN
51,Curacao,CUW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3033433248.16,3046364819.53,3026124115.73,2534327592.50,2739594359.59,3075180834.72,3281419347.37,3561178196.21,NaN,NaN
52,Cayman Islands,CYM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5166281293.19,5530178498.91,5941896599.57,5655357984.24,6060813808.15,6660161212.02,7241244269.46,NaN,NaN,NaN
53,Cyprus,CYP,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,22946570628.76,25754001367.54,26196667099.53,25555093854.30,30372642502.49,31218038929.09,35075423857.10,37634533331.89,NaN,NaN
54,Czechia,CZE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,221563575696.22,251992360762.24,256794209028.77,251109660602.54,290972714482.31,301831228325.56,345059295659.91,347034062928.48,NaN,NaN
55,Germany,DEU,GDP (current US$),NY.GDP.MKTP.CD,84619845881.26,96558204043.10,105895435234.34,112232503744.10,123330404665.09,134774688191.16,...,3765351626105.89,4055433215301.96,3959894794039.21,3941398957073.94,4355251953410.78,4201021706478.62,4562207532490.28,4685592577804.69,NaN,NaN
56,Djibouti,DJI,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2762581334.23,2913464658.09,3088851450.31,3144136196.62,3392796953.09,3562814908.76,3898447007.39,4152145939.98,NaN,NaN
57,Dominica,DMA,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,563355555.56,628244444.44,644259259.26,528944444.44,562911111.11,623062962.96,659311111.11,688881481.48,NaN,NaN
58,Denmark,DNK,GDP (current US$),NY.GDP.MKTP.CD,6361166544.50,7058361229.35,7953274741.29,8466044979.88,9677401337.17,10870670865.32,...,331610593961.99,355293374912.39,345401473012.61,355631021931.62,406110162088.05,400114306337.08,404651706117.56,424524722037.05,NaN,NaN
59,Dominican Republic,DOM,GDP (current US$),NY.GDP.MKTP.CD,672399700.00,654100200.00,824100000.00,940799900.00,1025599900.00,888100000.00,...,79070274743.17,84994732049.35,89146130744.72,78546672406.83,94850719516.71,113478087134.80,120456239153.74,124282245638.57,NaN,NaN
60,Algeria,DZA,GDP (current US$),NY.GDP.MKTP.CD,2723615451.30,2434747055.94,2001444543.92,2702982017.64,2909316435.29,3136284306.85,...,189880896903.07,194554483655.53,193459662090.68,164873415325.20,186231205262.08,225581644702.57,247923887214.65,269322281664.77,NaN,NaN
61,East Asia & Pacific (excluding high income),EAP,GDP (current US$),NY.GDP.MKTP.CD,80886065110.49,71247395333.07,64989160572.54,70288432260.53,81184317665.92,94594887799.95,...,15115625540264.80,16902110052652.30,17503274977303.30,17805166443182.20,21231425978691.40,21563881384135.80,21644412635340.60,22260810771875.10,NaN,NaN
62,Early-demographic dividend,EAR,GDP (current US$),NY.GDP.MKTP.CD,144721677770.05,157593209302.86,159435896119.12,175994009911.13,201822394409.76,218951522604.69,...,11320553240043.80,11478917653356.50,11686574879191.10,10823343545638.30,12695008338487.80,14034689936337.30,14933453330998.30,15808304487948.10,NaN,NaN
63,East Asia & Pacific,EAS,GDP (current US$),NY.GDP.MKTP.CD,157319051227.59,158550649387.07,162276885099.76,181110123774.70,207928170527.11,231441256707.03,...,24656162308335.20,26853593303707.30,27427259967363.20,27578839610232.40,31675719814404.90,31266291368260.60,31417826880875.00,32017179839273.00,NaN,NaN
64,Europe & Central Asia (excluding high income),ECA,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1499595960769.30,1477488205993.51,1508679974755.36,1446077189727.52,1680958734568.53,1820242864725.10,2143244215113.25,2451180144505.47,NaN,NaN
65,Europe & Central Asia,ECS,GDP (current US$),NY.GDP.MKTP.CD,426666341076.39,469524853748.68,513405546288.52,561372802906.34,620449239016.73,676603823141.81,...,21791487069281.70,23342642668393.30,23067540030248.60,22322527185686.70,25572901699926.60,25798700454390.60,27732942821913.50,29291828957768.80,NaN,NaN
66,Ecuador,ECU,GDP (current US$),NY.GDP.MKTP.CD,2069464937.20,1753850955.06,1518207703.49,1824343870.71,2244146102.98,2387047395.70,...,104467486000.00,107478961000.00,107595830000.00,95865473000.00,107179074000.00,116133121000.00,121147057000.00,124676074700.00,NaN,NaN
67,"Egypt, Arab Rep.",EGY,GDP (current US$),NY.GDP.MKTP.CD,4206270352.23,4494575611.21,4035462027.40,4187146231.57,4709245761.68,4948667540.41,...,248362771739.13,262588632526.73,318678815489.75,383817841547.10,424671765455.70,476747720364.74,395926075163.01,389059911003.57,NaN,NaN
68,Euro area,EMU,GDP (current US$),NY.GDP.MKTP.CD,251618036413.21,280078203910.32,309694923223.85,340786490149.60,377598986539.21,412774576471.61,...,12841960349280.80,13871778197583.70,13589774677631.30,13267554461613.60,14924551716260.40,14488160081806.70,15854782417877.00,16485444160371.00,NaN,NaN
69,Eritrea,ERI,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Spain,ESP,GDP (current US$),NY.GDP.MKTP.CD,12424514013.76,14238126759.73,16609632790.58,19631714759.65,21966876027.25,25479619606.53,...,1321754088818.83,1431642809327.06,1403496387686.27,1289783836971.21,1461244901852.69,1448850658406.62,1619481980719.64,1725671652742.19,NaN,NaN
71,Estonia,EST,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27469461919.12,31222632740.72,31873748770.03,31820771493.90,37201101170.58,38226641740.29,41470344395.11,43130419829.35,NaN,NaN
72,Ethiopia,ETH,GDP (current US$),NY.GDP.MKTP.CD,1610511693.84,1680859514.10,1747566307.10,1825058827.84,1984129185.60,2159998591.20,...,76366081766.67,83337901071.97,91834517112.63,98676811061.40,109070960371.86,123140304666.00,135874093202.49,149740297952.99,NaN,NaN
73,European Union,EUU,GDP (current US$),NY.GDP.MKTP.CD,285151593517.86,316957315284.25,350242479710.82,384746828593.34,426774574129.45,467012617276.64,...,14871313684625.80,16092403309151.50,15809073096211.40,15504055464107.40,17495226733585.20,17023612496380.40,18659133072074.80,19497115588443.60,NaN,NaN
74,Fragile and conflict affected situations,FCS,GDP (current US$),NY.GDP.MKTP.CD,34029503593.01,35534363196.69,39268957404.89,44880094682.09,40614223625.49,44620716060.02,...,1443031828638.41,1556210403398.50,1811454247630.60,1610227321244.27,1740335947472.93,1918272363969.18,1778723185468.20,1652895518697.74,NaN,NaN
75,Finland,FIN,GDP (current US$),NY.GDP.MKTP.CD,5279481824.13,5984433774.42,6407796042.70,6958916548.13,7848987792.54,8680393838.88,...,253846138440.00,273869255596.08,267014821129.41,270000311606.23,294223210496.12,280253099309.34,295021982462.75,298696961297.66,NaN,NaN
76,Fiji,FJI,GDP (current US$),NY.GDP.MKTP.CD,112328422.11,116987784.91,122906434.96,129454728.62,140032741.47,147084750.03,...,5353469174.48,5581425327.44,5344907153.47,4227719873.39,4158873156.18,4977861885.60,5476673518.14,5968125909.27,NaN,NaN
77,France,FRA,GDP (current US$),NY.GDP.MKTP.CD,61959085885.34,67158050215.05,75196980365.03,84227606649.87,93424179943.35,100927668584.29,...,2588868323334.71,2781576320884.39,2722793515171.76,2647926055110.05,2966433692008.09,2794788137066.94,3056250648138.29,3160442622465.08,NaN,NaN
78,Faroe Islands,FRO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,57954522.42,...,2980057377.88,3188600927.47,3266432734.23,3271813311.58,3699551717.11,3615241800.50,3943131022.23,4052937169.77,NaN,NaN
79,"Micronesia, Fed. Sts.",FSM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,359000000.00,392000000.00,394000000.00,372902700.00,391601900.00,415956900.00,441469400.00,471425099.49,NaN,NaN

In [97]:
ScimEn = pd.read_excel('data/scimagojr country rank 1996-2024.xlsx')

display(ScimEn)

,Rank,Country,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246
5,6,Germany,Western Europe,55466,54296,932195,185376,16.81,274
6,7,Russian Federation,Eastern Europe,49938,49562,268391,112125,5.37,123
7,8,Canada,Northern America,44877,44004,1082361,161133,24.12,305
8,9,Italy,Western Europe,42635,40695,767280,171442,18.00,227
9,10,South Korea,Asiatic Region,42534,42174,761076,124789,17.89,215
10,11,Iran,Middle East,35889,35484,798505,211983,22.25,218
11,12,France,Western Europe,33407,32698,637552,99244,19.08,235
12,13,Spain,Western Europe,32521,31781,726414,118758,22.34,233
13,14,Australia,Pacific Region,31047,30232,760284,99637,24.49,262
14,15,Brazil,Latin America,30840,30383,371926,84223,12.06,167
15,16,Turkey,Middle East,20947,20517,481017,87949,22.96,210
16,17,Saudi Arabia,Middle East,20790,20515,384481,71786,18.49,182
17,18,Poland,Eastern Europe,20315,19968,269331,69299,13.26,134
18,19,Taiwan,Asiatic Region,18849,18633,374534,43781,19.87,184
19,20,Malaysia,Asiatic Region,17977,17300,374139,68624,20.81,199
20,21,Norway,Western Europe,15367,15136,268479,42985,17.47,173
21,22,Netherlands,Western Europe,15139,14739,321083,35800,21.21,201
22,23,Sweden,Western Europe,13897,13644,340159,41929,24.48,198
23,24,Egypt,Africa/Middle East,13694,13485,252348,50651,18.43,160
24,25,Denmark,Western Europe,13599,13235,322821,42615,23.74,194
25,26,Ukraine,Eastern Europe,11724,11525,61760,36413,5.27,64
26,27,Portugal,Western Europe,10724,10135,184915,26743,17.24,140
27,28,Pakistan,Asiatic Region,10582,10466,184429,37337,17.43,135
28,29,Mexico,Latin America,10498,10161,134173,20482,12.78,118
29,30,Switzerland,Western Europe,10236,9984,238337,26601,23.28,178
30,31,Romania,Eastern Europe,10103,9965,98135,17422,9.71,106
31,32,Indonesia,Asiatic Region,9458,9337,75330,18928,7.96,89
32,33,Singapore,Asiatic Region,9238,8926,243101,18290,26.32,180
33,34,Greece,Western Europe,9181,8929,206555,26316,22.50,171
34,35,Hong Kong,Asiatic Region,8792,8623,239064,21290,27.19,174
35,36,South Africa,Africa,8699,8481,126636,18252,14.56,121
36,37,Belgium,Western Europe,8600,8344,175291,17678,20.38,160
37,38,Thailand,Asiatic Region,8100,7973,127006,15767,15.68,130
38,39,United Arab Emirates,Middle East,7399,7280,118550,14257,16.02,128
39,40,Finland,Western Europe,7053,6847,137533,17115,19.50,130
40,41,Austria,Western Europe,6714,6503,108366,12478,16.14,119
41,42,Czech Republic,Eastern Europe,6488,6391,69944,10700,10.78,90
42,43,Algeria,Africa,6310,6215,83076,16242,13.17,105
43,44,Bangladesh,Asiatic Region,5648,5608,60376,11007,10.69,84
44,45,Colombia,Latin America,5088,5035,72130,10291,14.18,101
45,46,Viet Nam,Asiatic Region,4597,4524,78718,9965,17.12,111
46,47,Iraq,Middle East,4500,4464,61766,12039,13.73,91
47,48,Nigeria,Africa,4321,4198,55745,9489,12.90,89
48,49,Chile,Latin America,4314,4224,59838,7790,13.87,91
49,50,Ireland,Western Europe,3882,3796,97019,9021,24.99,137
50,51,Morocco,Africa,3711,3655,42784,9813,11.53,76
51,52,Bulgaria,Eastern Europe,3619,3597,30690,5459,8.48,68
52,53,Tunisia,Africa,3550,3486,50784,7088,14.31,89
53,54,Hungary,Eastern Europe,3501,3422,50754,7514,14.50,88
54,55,New Zealand,Pacific Region,3494,3386,66685,6148,19.09,99
55,56,Israel,Middle East,3371,3291,67758,7005,20.10,104
56,57,Croatia,Eastern Europe,3356,3252,43816,5598,13.06,85
57,58,Argentina,Latin America,3337,3298,47076,5728,14.11,81
58,59,Serbia,Eastern Europe,3273,3224,46181,6074,14.11,85
59,60,Slovakia,Eastern Europe,3194,3112,27591,5764,8.64,59
60,61,Qatar,Middle East,3034,2987,55126,6697,18.17,92
61,62,Kuwait,Middle East,2674,2630,36149,3504,13.52,81
62,63,Jordan,Middle East,2554,2515,42993,6322,16.83,83
63,64,Kazakhstan,Asiatic Region,2487,2462,19675,4212,7.91,54
64,65,Slovenia,Eastern Europe,2320,2241,41243,3526,17.78,83
65,66,Ecuador,Latin America,2251,2231,18453,3224,8.20,52
66,67,Estonia,Eastern Europe,2130,2079,23321,5949,10.95,58
67,68,Lithuania,Eastern Europe,2122,2075,28349,3705,13.36,71
68,69,Oman,Middle East,2020,1953,31392,2787,15.54,80
69,70,Latvia,Eastern Europe,1570,1565,10698,2697,6.81,39
70,71,Lebanon,Middle East,1563,1555,28158,2464,18.02,79
71,72,Azerbaijan,Eastern Europe,1492,1483,8951,1956,6.00,48
72,73,Venezuela,Latin America,1475,1463,21522,1765,14.59,71
73,74,Peru,Latin America,1403,1391,7609,1745,5.42,36
74,75,Cyprus,Western Europe,1364,1321,29649,2236,21.74,71
75,76,Philippines,Asiatic Region,1335,1325,13542,2007,10.14,51
76,77,Sri Lanka,Asiatic Region,1094,1058,13258,1261,12.12,51
77,78,Ethiopia,Africa,1044,1035,13190,2190,12.63,51
78,79,Belarus,Eastern Europe,979,975,5866,1256,5.99,33
79,80,Macao,Asiatic Region,878,852,12268,911,13.97,54
80,81,Kenya,Africa,807,783,9464,851,11.73,42
81,82,Ghana,Africa,797,787,10247,1417,12.86,48
82,83,Bosnia and Herzegovina,Eastern Europe,759,746,6769,942,8.92,37
83,84,Libya,Africa,650,648,7418,737,11.41,42
84,85,Brunei Darussalam,Asiatic Region,536,519,12129,705,22.63,48
85,86,Uzbekistan,Asiatic Region,523,498,4106,957,7.85,32
86,87,Iceland,Western Europe,520,505,5110,753,9.83,36
87,88,Macedonia,Eastern Europe,474,463,6189,570,13.06,41
88,89,Palestine,Middle East,473,467,6760,779,14.29,41
89,90,Sudan,Africa,466,466,6324,348,13.57,42
90,91,Uruguay,Latin America,464,460,5035,609,10.85,36
91,92,Cameroon,Africa,460,458,5237,929,11.38,37
92,93,Cuba,Latin America,430,423,4884,489,11.36,36
93,94,Nepal,Asiatic Region,414,407,5708,780,13.79,40
94,95,Luxembourg,Western Europe,411,403,6133,494,14.92,39
95,96,Bahrain,Middle East,403,399,5234,418,12.99,37
96,97,Tanzania,Africa,363,359,5578,602,15.37,37
97,98,Moldova,Eastern Europe,340,310,760,280,2.24,12
98,99,Costa Rica,Latin America,315,311,2872,333,9.12,29
99,100,Malta,Western Europe,314,308,2670,316,8.50,26
100,101,Trinidad and Tobago,Latin America,311,308,3110,166,10.00,27
101,102,Paraguay,Latin America,276,275,2402,462,8.70,25
102,103,Syrian Arab Republic,Middle East,275,267,4704,355,17.11,35
103,104,Uganda,Africa,274,261,3352,315,12.23,28
104,105,Yemen,Middle East,266,265,5836,632,21.94,39
105,106,Puerto Rico,Latin America,259,255,2466,173,9.52,23
106,107,Rwanda,Africa,216,215,1577,204,7.30,21
107,108,Fiji,Pacific Region,203,201,2624,272,12.93,27
108,109,Armenia,Eastern Europe,201,201,2102,607,10.46,25
109,110,Mauritius,Africa,195,184,2166,111,11.11,24
110,111,Senegal,Africa,190,189,1698,158,8.94,20
111,112,Montenegro,Eastern Europe,186,186,2151,222,11.56,25
112,113,Mongolia,Asiatic Region,177,177,1420,155,8.02,19
113,114,Botswana,Africa,171,156,1234,135,7.22,19
114,115,Burkina Faso,Africa,161,159,2425,291,15.06,24
115,116,Georgia,Eastern Europe,161,156,1457,130,9.05,20
116,117,Panama,Latin America,157,156,584,78,3.72,13
117,118,Zambia,Africa,154,144,1379,85,8.95,20
118,119,Albania,Eastern Europe,145,144,1746,140,12.04,20
119,120,Bolivia,Latin America,127,123,1726,126,13.59,23
120,121,Angola,Africa,123,123,1018,16,8.28,16
121,122,Kyrgyzstan,Asiatic Region,121,120,654,76,5.40,15
122,123,Cambodia,Asiatic Region,119,118,1106,246,9.29,17
123,124,Benin,Africa,119,119,1182,115,9.93,20
124,125,El Salvador,Latin America,116,112,354,39,3.05,11
125,126,Malawi,Africa,116,115,1069,154,9.22,17
126,127,Zimbabwe,Africa,106,105,1512,124,14.26,20
127,128,Namibia,Africa,101,100,976,99,9.66,19
128,129,Mozambique,Africa,95,89,948,91,9.98,17
129,130,Myanmar,Asiatic Region,93,93,1066,98,11.46,16
130,131,Honduras,Latin America,90,90,227,52,2.52,7
131,132,Tajikistan,Asiatic Region,88,88,455,140,5.17,13
132,133,Afghanistan,Asiatic Region,84,84,1079,117,12.85,17
133,134,Côte d’Ivoire,Africa,82,81,1712,77,20.88,19
134,135,Togo,Africa,69,69,366,58,5.30,12
135,136,Laos,Asiatic Region,67,65,493,28,7.36,11
136,137,North Korea,Asiatic Region,66,66,624,63,9.45,15
137,138,Dominican Republic,Latin America,62,61,314,31,5.06,9
138,139,Monaco,Western Europe,59,59,343,35,5.81,11
139,140,Congo,Africa,59,59,501,21,8.49,12
140,141,Jamaica,Latin America,55,55,349,28,6.35,10
141,142,Democratic Republic Congo,Africa,54,54,399,44,7.39,12
142,143,Mali,Africa,51,51,994,54,19.49,17
143,144,Bhutan,Asiatic Region,47,47,363,27,7.72,11
144,145,Nicaragua,Latin America,46,46,180,11,3.91,9
145,146,Niger,Africa,45,44,510,44,11.33,14
146,147,Madagascar,Africa,43,43,583,36,13.56,12
147,148,Somalia,Africa,39,38,114,6,2.92,6
148,149,Papua New Guinea,Pacific Region,35,33,207,15,5.91,9
149,150,Guatemala,Latin America,34,32,397,17,11.68,7
150,151,Turkmenistan,Asiatic Region,33,33,225,75,6.82,9
151,152,Mauritania,Africa,32,32,355,32,11.09,9
152,153,Gabon,Africa,28,28,208,9,7.43,8
153,154,Sierra Leone,Africa,27,27,297,15,11.00,10
154,155,Djibouti,Africa,26,26,200,20,7.69,6
155,156,Faroe Islands,Western Europe,22,22,201,23,9.14,8
156,157,Eswatini,Africa,22,22,168,1,7.64,7
157,158,Chad,Africa,21,21,104,17,4.95,5
158,159,Liechtenstein,Western Europe,20,20,390,12,19.50,8
159,160,Liberia,Africa,19,19,262,16,13.79,9
160,161,Lesotho,Africa,19,18,187,15,9.84,6
161,162,Burundi,Africa,19,19,203,16,10.68,8
162,163,Cape Verde,Africa,17,17,238,16,14.00,6
163,164,Eritrea,Africa,16,16,282,3,17.63,8
164,165,Guinea,Africa,16,16,359,4,22.44,5
165,166,Barbados,Latin America,16,16,103,10,6.44,8
166,167,Suriname,Latin America,15,15,77,1,5.13,4
167,168,Maldives,Asiatic Region,12,12,236,10,19.67,6
168,169,Solomon Islands,Pacific Region,12,12,70,10,5.83,4
169,170,Gambia,Africa,11,11,51,4,4.64,4
170,171,Republic of South Sudan,Africa,11,11,51,0,4.64,3
171,172,French Polynesia,Pacific Region,10,10,136,7,13.60,5
172,173,Guyana,Latin America,9,9,26,0,2.89,3
173,174,Guadeloupe,Latin America,9,9,52,0,5.78,2
174,175,Timor-Leste,Asiatic Region,9,9,28,1,3.11,4
175,176,Bermuda,Latin America,8,8,29,0,3.63,2
176,177,Samoa,Pacific Region,8,8,73,7,9.13,3
177,178,French Guiana,Latin America,8,8,47,2,5.88,4
178,179,San Marino,Western Europe,7,7,80,4,11.43,5
179,180,Reunion,Africa,7,7,26,1,3.71,3
180,181,New Caledonia,Pacific Region,7,7,105,7,15.00,4
181,182,Central African Republic,Africa,7,7,18,12,2.57,3
182,183,Greenland,Western Europe,6,6,200,1,33.33,5
183,184,Equatorial Guinea,Africa,6,6,52,0,8.67,2
184,185,Belize,Latin America,5,5,59,3,11.80,4
185,186,Comoros,Africa,4,4,15,0,3.75,2
186,187,Netherlands Antilles,Latin America,4,4,30,0,7.50,2
187,188,Haïti,Latin America,4,4,9,1,2.25,2
188,189,Seychelles,Africa,3,3,13,2,4.33,2
189,190,Andorra,Western Europe,3,3,27,0,9.00,2
190,191,Guam,Pacific Region,3,3,22,2,7.33,2
191,192,Gibraltar,Western Europe,3,3,152,2,50.67,2
192,193,Bahamas,Latin America,3,3,8,0,2.67,2
193,194,American Samoa,Pacific Region,3,3,2,0,0.67,1
194,195,Antigua and Barbuda,Latin America,2,2,1,1,0.50,1
195,196,Cayman Islands,Latin America,2,2,8,0,4.00,1
196,197,Tonga,Pacific Region,2,2,30,1,15.00,2
197,198,Sao Tome and Principe,Africa,2,2,72,1,36.00,2
198,199,Saint Helena,Africa,2,2,105,0,52.50,2
199,200,Federated States of Micronesia,Pacific Region,2,2,3,0,1.50,1
200,201,Curaçao,Latin America,2,2,6,1,3.00,1
201,202,Saint Vincent and the Grenadines,Latin America,2,2,11,1,5.50,2
202,203,Svalbard and Jan Mayen,Western Europe,2,2,0,0,0.00,0
203,204,British Indian Ocean Territory,Africa,2,2,87,0,43.50,1
204,205,Kiribati,Pacific Region,2,2,87,0,43.50,2
205,206,Nauru,Pacific Region,2,2,3,0,1.50,1
206,207,Palau,Pacific Region,1,1,0,0,0.00,0
207,208,Saint Lucia,Latin America,1,1,0,0,0.00,0
208,209,Grenada,Latin America,1,1,28,0,28.00,1
209,210,Montserrat,Latin America,1,1,9,0,9.00,1
210,211,Dominica,Latin America,1,1,1,0,1.00,1
211,212,Christmas Island,Pacific Region,1,1,0,0,0.00,0
212,213,Guinea-Bissau,Africa,1,1,55,7,55.00,1
213,214,Marshall Islands,Pacific Region,1,1,1,0,1.00,1

In [98]:
def answer_one():
    year_col = [str(year) for year in range(2006, 2016)]
    GDP_years = GDP.loc[:, ['Country Name'] + year_col]
    top15 = ScimEn.head(15)

    # Iran was not displayed correctly ('Iran ' instead of 'Iran')
    energy['Country'] = energy['Country'].str.strip()

    sub_merge = pd.merge(top15, energy, left_on='Country', right_on='Country', how='inner')
    merge = pd.merge(sub_merge, GDP_years, left_on='Country', right_on='Country Name', how='inner')
    merge.set_index('Country', inplace=True)

    columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
    merge = merge[columns]
    return merge

answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,472465,470142,6591474,4594673,13.95,380,127191000000,93,19.75,2791498472804.33,3604055822571.63,4667346414521.95,5189577094997.58,6192564874453.29,7671757207851.29,8673664713189.24,9743124247267.24,10674533168257.40,11280814787468.90
United States,2,222772,217929,4131736,1119917,18.55,491,90838000000,286,11.57,13815586948000.00,14474226905000.00,14769857911000.00,14478064934000.00,15048964444000.00,15599728123000.00,16253972230000.00,16843190993000.00,17550680174000.00,18206020741000.00
India,3,96975,94714,1243636,479638,12.82,258,33195000000,26,14.97,940259888787.72,1216736438834.96,1198895139005.92,1341888016994.90,1675615519484.96,1823051829894.55,1827637590410.41,1856721507621.58,2039126479154.52,2103588360044.94
United Kingdom,4,61946,60287,1326766,207337,21.42,313,7920000000,124,10.60,2719558417663.29,3104699879951.98,2945251838235.29,2429358155475.93,2496740681057.14,2675590034128.66,2719715961539.83,2796908333283.39,3085362169410.29,2945579890258.46
Japan,5,61939,61307,813472,166907,13.13,246,18984000000,149,10.23,4601663122649.92,4579750920354.81,5106679115127.30,5289493117993.89,5759071769013.11,6233147172341.35,6272362996105.03,5212328181166.18,4896994405353.29,4444930651964.18
Germany,6,55466,54296,932195,185376,16.81,274,13261000000,165,17.90,3046308753670.58,3484056680854.91,3808197720125.00,3478545516683.59,3467093769666.67,3823575803793.78,3596483233406.25,3807023797050.99,3964870735760.77,3425099578746.09
Russian Federation,7,49938,49562,268391,112125,5.37,123,30709000000,214,17.29,989932071352.54,1299703478481.65,1660848058303.11,1222645900055.70,1524916715223.95,2045922753398.04,2208293553878.42,2292470078346.22,2059241589895.01,1363482182197.71
Canada,8,44877,44004,1082361,161133,24.12,305,10431000000,296,61.95,1319264809590.97,1468820407783.26,1552989690721.65,1374625142157.29,1617343367486.26,1793326630174.52,1828366481521.60,1846597421834.98,1805749878439.94,1556508816217.14
Italy,9,42635,40695,767280,171442,18.00,227,6530000000,109,33.67,1958563654385.64,2222524108127.65,2417508414187.19,2209484319012.65,2144936254535.00,2306974020278.21,2097929495121.68,2153225581941.46,2173255507985.84,1845428048839.10
South Korea,10,42534,42174,761076,124789,17.89,215,11007000000,221,2.28,1095175538508.19,1220911904593.06,1091580692542.34,983065242417.36,1192830015737.68,1307103477219.10,1335343586437.67,1434669686501.84,1556252422020.44,1539212301135.55
Iran,11,35889,35484,798505,211983,22.25,218,9172000000,119,5.71,265602187403.64,349736591832.42,406070949553.88,414059094949.06,487069570463.77,629082257472.37,644019315003.54,500399839839.88,462284793280.83,409191686496.68
France,12,33407,32698,637552,99244,19.08,235,10597000000,166,17.02,2317861544690.82,2655816911866.56,2926802941585.86,2700075882518.98,2646230027988.34,2870408553990.28,2683007095787.23,2816077607875.26,2861236112552.42,2442483452642.50
Spain,13,32521,31781,726414,118758,22.34,233,4923000000,106,37.97,1261846683275.29,1476746276854.51,1636115447612.50,1496587590847.66,1427989078916.67,1487568659241.25,1330994811670.31,1362186923157.65,1380244561361.96,1206164777553.12
Australia,14,31047,30232,760284,99637,24.49,262,5386000000,231,11.81,749708370332.99,856603595823.19,1058448244063.77,931761689770.84,1152566632022.13,1402939868653.40,1552728401401.58,1583737461925.39,1474677007565.64,1356805839935.90
Brazil,15,30840,30383,371926,84223,12.06,167,12149000000,59,69.65,1107626711163.23,1397114247188.89,1695855391757.96,1666996294252.12,2208838108484.35,2616156606579.21,2465228293706.86,2472819362043.74,2456043766032.38,1802211999456.42

In [99]:
def answer_two():
    Top15 = answer_one()
    avgGDP = Top15[[str(year) for year in range(2006, 2016)]].mean(axis=1, skipna=True)
    avgGDP = avgGDP.sort_values(ascending=False)
    return avgGDP

answer_two()

Country
United States        15704029340300.00
China                 7048893680338.29
Japan                 5239642145206.91
Germany               3590125558975.86
United Kingdom        2791876536100.43
France                2692000013149.83
Italy                 2152982940441.44
Brazil                1988889078066.52
Russian Federation    1666745638113.24
Canada                1616359264592.76
India                 1602352077023.45
Spain                 1406644481049.09
South Korea           1275614486711.32
Australia             1211997711149.48
Iran                   456751628629.61
dtype: float64

In [100]:
def answer_three():
    Top15 = answer_one()
    avgGDP = Top15[[str(year) for year in range(2006, 2016)]].mean(axis=1, skipna=True)
    country = avgGDP.sort_values(ascending=False).index[5]
    change = Top15.loc[country, '2015'] - Top15.loc[country, '2006']

    return float(change)

answer_three()

124621907951.68018

In [101]:
def answer_four():
    Top15 = answer_one()
    Top15['Ratio'] = Top15['Self-citations'] / Top15['Citations']
    max_ratio = Top15['Ratio'].max()
    country = Top15['Ratio'].idxmax()
    return country, float(max_ratio)

answer_four()

('China', 0.6970630544852335)

In [102]:
def answer_five():
    Top15 = answer_one()
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    third_country = Top15.sort_values('Population', ascending=False).index[2]
    return third_country

answer_five()

'United States'

In [103]:
def answer_six():
    Top15 = answer_one()
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable documents per capita'] = Top15['Citable documents'] / Top15['Population']
    corr = Top15['Citable documents per capita'].corr(Top15['Energy Supply per Capita'])
    return float(corr)


answer_six()

0.6905473831164103

In [104]:
def answer_seven():
    Top15 = answer_one()
    ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}

    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Continent'] = Top15.index.map(ContinentDict)
    df_columns = ['size', 'sum', 'mean', 'std']
    Grouped_df = Top15.groupby('Continent')['Population'].agg(df_columns)
    Grouped_df.columns = df_columns

    return Grouped_df


answer_seven()

               size           sum         mean          std
Continent
Asia              5 2898666386.61 579733277.32 679097888.37
Australia         1   23316017.32  23316017.32          NaN
Europe            6  457929667.22  76321611.20  34647667.07
North America     2  352855249.48 176427624.74 199669644.86
South America     1  205915254.24 205915254.24          NaN