In [33]:
import pandas as pd
import os
from sqlalchemy import create_engine
from sqlalchemy import text

In [34]:
def get_data(data_dir):
    files_to_load = {
        "customers": "customers.csv",
        "products": "products.csv",
        "orders": "orders.csv",
        "order_items": "order_items.csv"
    }

    dataframes = {}

    for name, file_name in files_to_load.items():
        file_path = os.path.join(data_dir, file_name)
        try:
            cols = pd.read_csv(file_path, nrows=0).columns
            dtype_dict = {col: 'Int64' for col in cols if 'id' in col.lower()}

            dataframes[name] = pd.read_csv(file_path, dtype=dtype_dict)
            print(f"Sucssesfully downloaded {file_name}: {dataframes[name].shape[0]} rows, {dataframes[name].shape[1]} cols.")
        except FileNotFoundError:
            print(f"Error file not found: {file_path}")
        except Exception as e:
            print(f"Error during downloading {file_name}: {e}")

    customers_df = dataframes.get("customers")
    products_df = dataframes.get("products")
    orders_df = dataframes.get("orders")
    order_items_df = dataframes.get("order_items")

    return customers_df, products_df, orders_df, order_items_df

# Transforming customers data frame

In [35]:
def clean_customer(df):
    cleaned_df = df.copy()

    # Drop duplicate customer ID keeping the first occurrence.
    # Why: A primary key must be unique to load properly into a relational database.
    cleaned_df = cleaned_df.drop_duplicates(subset=['customer_id'], keep='first')

    # Fill missing customer_id by incrementing the previous rows ID by 1.
    # Why: Ensures every record has a unique identifier without dropping potentially valuable data.
    for ind in cleaned_df[cleaned_df['customer_id'].isna()].index:
        if ind > 0:
            cleaned_df.loc[ind, 'customer_id'] = cleaned_df.loc[ind - 1, 'customer_id'] + 1

    # Fill missing emails with unknown_email.
    # Why: Standardizes missing data.
    cleaned_df['email'] = cleaned_df['email'].fillna('unknown_email')

    # Identify invalid email formats and replace them with unknown_email.
    # Why: Standardizes broken data while preserving the rest of the customers record.
    invalid_email_mask = ~cleaned_df['email'].str.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', na=False)
    cleaned_df.loc[invalid_email_mask & (cleaned_df['email'] != 'unknown_email'), 'email'] = 'unknown_email'
    
    # Coerce invalid dates in created_at to NaT.
    # Why: Preserves the datetime64 data type in pandas, allowing it to correctly map to SQL TIMESTAMP with NULL values.
    cleaned_df['created_at'] = pd.to_datetime(cleaned_df['created_at'], errors='coerce')

    return cleaned_df

# Transforming products data frame

In [36]:
def clean_products(df):
    cleaned_df = df.copy()

    # Drop duplicate product ID keeping the first occurrence.
    cleaned_df = cleaned_df.drop_duplicates(subset=['product_id'], keep='first')

    # Fill missing product_ids by incrementing the previous rows ID by 1.
    for ind in cleaned_df[cleaned_df['product_id'].isna()].index:
        if ind > 0:
            cleaned_df.loc[ind, 'product_id'] = cleaned_df.loc[ind - 1, 'product_id'] + 1

    # Fill missing category and name with Unknown.
    # Why: Prevents NULL constraint issues and categorizes missing data for analysts.
    cleaned_df['category'] = cleaned_df['category'].fillna('Unknown')
    cleaned_df['name'] = cleaned_df['name'].fillna('Unknown')

    # Take the absolute value of price.
    # Why: Assumed negative prices are human entry typos.
    cleaned_df['price'] = cleaned_df['price'].abs()

    # Replace zero prices with the median price of all strictly positive priced products.
    # Why: Keeps the product record for inventory analysis while maintaining a realistic price proxy.
    median_price = cleaned_df.loc[cleaned_df['price'] > 0, 'price'].median()
    cleaned_df.loc[cleaned_df['price'] == 0, 'price'] = median_price

    return cleaned_df

# Transforming orders data frame

In [37]:
def clean_orders(df):
    cleaned_df = df.copy()

    # Drop duplicate order ID keeping the first occurrence.
    cleaned_df = cleaned_df.drop_duplicates(subset=['order_id'], keep='first')

    # Fill missing order_ids by incrementing the previous rows. ID by 1.
    for ind in cleaned_df[cleaned_df['order_id'].isna()].index:
        if ind > 0:
            cleaned_df.loc[ind, 'order_id'] = cleaned_df.loc[ind - 1, 'order_id'] + 1

    # Drop rows where customer_id is missing.
    # Why: An order without a customer is an orphan record that would violate foreign key constraints.
    cleaned_df = cleaned_df.dropna(subset=['customer_id'])

    # Convert order_status to lowercase.
    # Why: Standardizes categorical values for accurate aggregation.
    cleaned_df['order_status'] = cleaned_df['order_status'].str.lower()

    valid_statuses = ['returned', 'completed', 'cancelled', 'pending']
    cleaned_df.loc[~cleaned_df['order_status'].isin(valid_statuses), 'order_status'] = 'unknown'

    # Coerce invalid dates in created_at to NaT.
    cleaned_df['created_at'] = pd.to_datetime(cleaned_df['created_at'], errors='coerce')

    return cleaned_df

# Transforming order items data frame

In [38]:
def clean_order_items(df):
    cleaned_df = df.copy()

    # Drop duplicate order item ID keeping the first occurrence.
    cleaned_df = cleaned_df.drop_duplicates(subset=['order_item_id'], keep='first')

    # Fill missing order_item_ids by incrementing the previous rows ID by 1.
    for ind in cleaned_df[cleaned_df['order_item_id'].isna()].index:
        if ind > 0:
            cleaned_df.loc[ind, 'order_item_id'] = cleaned_df.loc[ind - 1, 'order_item_id'] + 1

    # Drop rows missing order_id or product_id.
    # Why: Necessary to maintain referential integrity (foreign keys) and ensures revenue calculations have valid products.
    cleaned_df = cleaned_df.dropna(subset=['order_id'])
    cleaned_df = cleaned_df.dropna(subset=['product_id'])

    # Replace negative quantity values with 0.
    # Why: Quantity cannot be negative. Setting it to 0 neutralizes its impact on revenue sums rather than artificially decreasing the sum.
    cleaned_df.loc[cleaned_df['quantity'] < 0, 'quantity'] = 0

    return cleaned_df

# Loading data frames to the database

In [39]:
def load_data_to_postgres(customers_df, products_df, orders_df, order_items_df):
    
    # Ideally this should be in .env
    DB_USER = 'postgres'
    DB_PASSWORD = 'password123'
    DB_HOST = 'localhost' 
    DB_PORT = '5432'
    DB_NAME = 'ecommerce_db'
    
    connection_string = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
    
    try:
        engine = create_engine(connection_string)
        
        customers_df.to_sql('customers', engine, if_exists='replace', index=False)
        print("Table 'customers' loaded to PostgreSQL.")
        
        products_df.to_sql('products', engine, if_exists='replace', index=False)
        print("Table 'products' loaded to PostgreSQL.")
        
        orders_df.to_sql('orders', engine, if_exists='replace', index=False)
        print("Table 'orders' loaded to PostgreSQL.")
        
        order_items_df.to_sql('order_items', engine, if_exists='replace', index=False)
        print("Table 'order_items' loaded to PostgreSQL.")
        
    except Exception as e:
        print(f"Error connecting or loading to PostgreSQL: {e}")

# Creating analytical tables

In [40]:
def create_analytical_tables():
    
    # Ideally this should also be in .env
    DB_USER = 'postgres'
    DB_PASSWORD = 'password123'
    DB_HOST = 'localhost' 
    DB_PORT = '5432'
    DB_NAME = 'ecommerce_db'
    
    connection_string = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
    
    sql_queries = [
        """
        DROP TABLE IF EXISTS customer_summary;
        CREATE TABLE customer_summary AS
        SELECT 
            c.customer_id,
            c.email,
            c.country,
            COUNT(DISTINCT o.order_id) AS total_orders,
            COALESCE(SUM(oi.quantity * p.price), 0) AS total_spent
        FROM customers c
        LEFT JOIN orders o ON c.customer_id = o.customer_id
        LEFT JOIN order_items oi ON o.order_id = oi.order_id
        LEFT JOIN products p ON oi.product_id = p.product_id
        GROUP BY c.customer_id, c.email, c.country;
        """,
        """
        DROP TABLE IF EXISTS product_performance;
        CREATE TABLE product_performance AS
        SELECT 
            p.product_id,
            p.name,
            p.category,
            COALESCE(SUM(oi.quantity), 0) AS total_quantity_sold,
            COALESCE(SUM(oi.quantity * p.price), 0) AS total_revenue
        FROM products p
        LEFT JOIN order_items oi ON p.product_id = oi.product_id
        GROUP BY p.product_id, p.name, p.category;
        """
    ]
    try:
        engine = create_engine(connection_string)
        with engine.begin() as conn:  
            for query in sql_queries:
                conn.execute(text(query))
        print("Analytical output tables created successfully in PostgreSQL.")
    except Exception as e:
        print(f"Error creating analytical tables: {e}")

# Running ELT pipeline

In [41]:
def run_elt_pipeline(data_dir):
    print(f"Starting ELT pipeline using data from: {data_dir}")
    
    customers_df, products_df, orders_df, order_items_df = get_data(data_dir)
    
    customers_clean_df = clean_customer(customers_df)
    products_clean_df = clean_products(products_df)
    orders_clean_df = clean_orders(orders_df)
    order_items_clean_df = clean_order_items(order_items_df)
    
    load_data_to_postgres(customers_clean_df, products_clean_df, orders_clean_df, order_items_clean_df)
    create_analytical_tables()
    
    print("ELT pipeline finished successfully!")

pipeline_data_dir = os.path.join('.', 'data', 'raw') 
run_elt_pipeline(pipeline_data_dir)

Starting ELT pipeline using data from: .\data\raw
Sucssesfully downloaded customers.csv: 357 rows, 4 cols.
Sucssesfully downloaded products.csv: 155 rows, 4 cols.
Sucssesfully downloaded orders.csv: 456 rows, 4 cols.
Sucssesfully downloaded order_items.csv: 914 rows, 4 cols.
Table 'customers' loaded to PostgreSQL.
Table 'products' loaded to PostgreSQL.
Table 'orders' loaded to PostgreSQL.
Table 'order_items' loaded to PostgreSQL.
Analytical output tables created successfully in PostgreSQL.
ELT pipeline finished successfully!

# Showing results

In [42]:

connection_string = 'postgresql://postgres:password123@localhost:5432/ecommerce_db'
engine = create_engine(connection_string)

print("--- Customer Summary ---")
customer_summary_df = pd.read_sql("SELECT * FROM customer_summary LIMIT 10;", engine)
display(customer_summary_df)

print("\n--- Product Performance ---")
product_performance_df = pd.read_sql("SELECT * FROM product_performance LIMIT 10;", engine)
display(product_performance_df)

--- Customer Summary ---

   customer_id               email country  total_orders  total_spent
0            1   user1@example.com      DE             1      2734.20
1            2   user2@example.com      PL             2      2713.70
2            3   user3@example.com      DE             1         0.00
3            4   user4@example.com      CZ             1      1206.74
4            5   user5@example.com      US             1      2411.51
5            6   user6@example.com      PL             2     17543.76
6            7   user7@example.com      CZ             0         0.00
7            8   user8@example.com      CZ             0         0.00
8            9   user9@example.com      SE             2      8098.58
9           10  user10@example.com      UA             3     25054.40

--- Product Performance ---

,product_id,name,category,total_quantity_sold,total_revenue
0,1122,Toys Product 1122,Toys,32.0,39296.00
1,1120,Sports Product 1120,Sports,6.0,2044.74
2,1051,Electronics Product 1051,Electronics,23.0,1788.71
3,1142,Books Product 1142,Books,22.0,21858.76
4,1127,Stationery Product 1127,Stationery,13.0,13710.32
5,1099,Books Product 1099,Books,19.0,8933.04
6,1145,Toys Product 1145,Toys,12.0,9233.88
7,1012,Books Product 1012,Books,11.0,15960.67
8,1055,Toys Product 1055,Toys,19.0,15811.80
9,1117,Toys Product 1117,Toys,22.0,3610.42